name: flutter_widgets
description: A new Flutter project for widgets.

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
